name: dado_app_fluttter
description: Aplicación de dados 3D con estilo Cupertino
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  model_viewer_plus: ^1.7.0
  flutter_svg: ^2.0.9
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.14.3"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/

flutter_launcher_icons:
  android: true  # Generar iconos para Android (o "launcher_icon")
  ios: true      # Generar iconos para iOS
  image_path: "assets/images/logo_app_dado.jpeg" # Ruta a tu imagen de logo
  # Opcional: si tu imagen ya tiene el formato adaptativo de Android Oreo+
  # adaptive_icon_background: "#ffffff" # Color de fondo para iconos adaptativos
  # adaptive_icon_foreground: "assets/images/logo_foreground.png" # Imagen de primer plano para iconos adaptativos
  min_sdk_android: 21 # Opcional: SDK mínimo de Android
